fuse: Temporarily run in pid=host, to make the thing work in Ubuntu 16.04
We can get rid of this after kernel get rid of restriction of pid namespace
for fuse(#204)

Also disable killing process part of integration test script for now,
otherwise we may kill longhorn in another namespace.

diff --git a/scripts/integration-test b/scripts/integration-test
--- a/scripts/integration-test
+++ b/scripts/integration-test
@@ -1,25 +1,27 @@
 #!/bin/bash
 set -e
 
-killall longhorn ssync || true
-
-running=""
-for i in `seq 10`
-do
-	running=`ps aux|grep longhorn|grep -v grep || true`
-	if [ -z "$running" ]
-	then
-		break
-	fi
-	echo Wait one more second for longhorn process to stop
-	sleep 1
-done
-if [ "$running" ]
-then
-	echo Failed to wait for longhorn process stop
-	echo $running
-	exit -1
-fi
+# Don't want to kill longhorn in another namespace for now
+#
+#killall longhorn ssync || true
+#
+#running=""
+#for i in `seq 10`
+#do
+#	running=`ps aux|grep longhorn|grep -v grep || true`
+#	if [ -z "$running" ]
+#	then
+#		break
+#	fi
+#	echo Wait one more second for longhorn process to stop
+#	sleep 1
+#done
+#if [ "$running" ]
+#then
+#	echo Failed to wait for longhorn process stop
+#	echo $running
+#	exit -1
+#fi
 
 temp=$(mktemp -d)
 temp2=$(mktemp -d)
